# services:
#   postgres:
#     image: pgvector/pgvector:pg16
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: test_series_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   ollama:
#     image: ollama/ollama:latest
#     restart: unless-stopped
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama:/root/.ollama

# volumes:
#   pgdata:
#   ollama:
